pipeline {
    agent any
    tools {nodejs 'node'}
    environment {
        CI = 'true'
        SSH_CREDENTIALS = credentials('a6167c9b-e084-4ad5-87e3-ce99c295fdb3')
        VM_IP = '20.196.92.64'
        REMOTE_PATH = '/home/azusr/nodeprojectdeployment'
        APP_PATH = '/simple-node-js-react-npm-app'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/m-adilazan/simple-node-js-react-npm-app.git'
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Copy Files to Azure VM') {
            steps {
                script {
                    sh """
                        scp -r -o StrictHostKeyChecking=no -i ${SSH_CREDENTIALS} ${APP_PATH} azusr@${VM_IP}:${REMOTE_PATH}
                    """
                }
            }
        }
        stage('Deploy Application') {
            steps {
                script {
                    sh """
                        ssh -o StrictHostKeyChecking=no -i ${SSH_CREDENTIALS} azusr@${VM_IP} << 'EOF'
                            cd ${REMOTE_PATH}
                            npm install
                            npm start &
                        EOF
                    """
                }
            }
        }
    }
}
