pipeline {
    agent {
        docker {
            image 'node:22-alpine3.19'
            args '-p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        CI = 'true'
        VM_IP = '20.196.92.64'
        REMOTE_PATH = '/home/azusr/nodeprojectdeployment'
        APP_PATH = '/simple-node-js-react-npm-app'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/m-adilazan/simple-node-js-react-npm-app.git'
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy Application') {
            steps {
                sshagent(['a6167c9b-e084-4ad5-87e3-ce99c295fdb3']) {
                    sh '''
                        # Run SSH commands on the Jenkins host instead of inside Docker
                        ssh -o StrictHostKeyChecking=no azusr@${VM_IP} "cd ${REMOTE_PATH} && npm install && npm start &"
                    '''            
                }
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}
