pipeline {
    agent {
        docker {
            image 'node:22-alpine3.19'
            args '-p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        CI = 'true'
        VM_IP = '20.196.92.64'
        REMOTE_PATH = '/home/azusr/nodeprojectdeployment'
        APP_PATH = '/simple-node-js-react-npm-app'
    }
    stages {
        stage('Create Dockerfile') {
            steps {
                script {
                    // Create the Dockerfile dynamically
                    writeFile file: 'Dockerfile', text: '''
                        # Use the official Node.js 22 image based on Alpine
                        FROM node:22-alpine

                        # Set the working directory
                        WORKDIR /usr/src/app

                        # Copy package.json and package-lock.json
                        COPY package*.json ./

                        RUN apk add --no-cache openssh-client

                        # Install dependencies
                        RUN npm install

                        # Copy the rest of the application files
                        COPY . .

                        # Expose the application port
                        EXPOSE 3000

                        # Command to run the application
                        CMD ["npm", "start"]
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                git 'https://github.com/m-adilazan/simple-node-js-react-npm-app.git'
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deploy Application') {
            steps {
                 script {
            sshagent(['a6167c9b-e084-4ad5-87e3-ce99c295fdb3']) {
                sh '''
                    # Run SSH commands on the Jenkins host instead of inside Docker
                    ssh -o StrictHostKeyChecking=no azusr@${VM_IP} "cd ${REMOTE_PATH} && npm install && npm start &"
                '''
            }
            input message: 'Finished using the web site? (Click "Proceed" to continue)'
        }
            }
        }
    }
}
